//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotesMarketplace.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Download
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Download()
        {
            this.NotesReports = new HashSet<NotesReport>();
            this.NotesReviews = new HashSet<NotesReview>();
        }
    
        public int DownloadID { get; set; }
        public int NoteID { get; set; }
        public int SellerID { get; set; }
        public int BuyerID { get; set; }
        public bool IsAllowed { get; set; }
        public int AttachmentsID { get; set; }
        public bool IsDownloaded { get; set; }
        public Nullable<System.DateTime> DownloadDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsPaid { get; set; }
        public string NoteTitle { get; set; }
        public int NoteCategory { get; set; }
        public Nullable<decimal> PurchasedPrice { get; set; }
    
        public virtual User User { get; set; }
        public virtual NoteCategory NoteCategory1 { get; set; }
        public virtual Note Note { get; set; }
        public virtual User User1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotesReport> NotesReports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotesReview> NotesReviews { get; set; }
    }
}
